services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ${SITE_PATH}:/var/www/app
      - ./nginx-${NGINX_CONF_TYPE}.conf:/etc/nginx/conf.d/default.conf
      - ./nginx-upstream.conf:/etc/nginx/conf.d/upstream.conf
    networks:
      - network
    depends_on:
      - php
  php:
    build: ./images/${PHP_VERSION}fpm
    volumes:
      - ${SITE_PATH}:/var/www/app
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - network
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    ports:
      - 33060:3306
    volumes:
      - ${SITE_PATH}:/var/www/app
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    command: ["--default-authentication-plugin=mysql_native_password"]
    networks:
      - network

networks:
  network:

volumes:
  db:
